// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc4MtRPseTrgxJn4KbQ1Ermrn6KTNw3ds',
    appId: '1:555308095726:android:70a5409e3da316565c3bff',
    messagingSenderId: '555308095726',
    projectId: 'job-portal-7ad5d',
    storageBucket: 'job-portal-7ad5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmTXUyg6Z3joGvkEbQ5vEW-2F2s-4kAbc',
    appId: '1:555308095726:ios:796880426b2c16a75c3bff',
    messagingSenderId: '555308095726',
    projectId: 'job-portal-7ad5d',
    storageBucket: 'job-portal-7ad5d.firebasestorage.app',
    iosBundleId: 'com.example.jobportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRfckfmxhYkfuWdLfhn6CM-cSEts_x1Wk',
    appId: '1:555308095726:web:f93b472c7117e7e25c3bff',
    messagingSenderId: '555308095726',
    projectId: 'job-portal-7ad5d',
    authDomain: 'job-portal-7ad5d.firebaseapp.com',
    storageBucket: 'job-portal-7ad5d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfckfmxhYkfuWdLfhn6CM-cSEts_x1Wk',
    appId: '1:555308095726:web:36fbbd68d665a8905c3bff',
    messagingSenderId: '555308095726',
    projectId: 'job-portal-7ad5d',
    authDomain: 'job-portal-7ad5d.firebaseapp.com',
    storageBucket: 'job-portal-7ad5d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmTXUyg6Z3joGvkEbQ5vEW-2F2s-4kAbc',
    appId: '1:555308095726:ios:796880426b2c16a75c3bff',
    messagingSenderId: '555308095726',
    projectId: 'job-portal-7ad5d',
    storageBucket: 'job-portal-7ad5d.firebasestorage.app',
    iosBundleId: 'com.example.jobportal',
  );

}